import { auth } from "@clerk/nextjs/server";
import { NextRequest } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getSTTProvider, getDefaultSTTProvider } from "@/lib/ai/stt-factory";

const transcribeSchema = z.object({
  mediaFileId: z.string(),
  provider: z.enum(["WHISPER", "DEEPGRAM", "ASSEMBLYAI"]).optional(),
  language: z.string().default("en"),
  diarization: z.boolean().default(false),
  punctuation: z.boolean().default(true),
  wordTimestamps: z.boolean().default(true),
});

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { userId } = await auth();
    if (!userId) return Response.json({ error: "Unauthorized" }, { status: 401 });

    const { id: projectId } = await params;
    const user = await prisma.user.findUnique({ where: { clerkId: userId } });
    if (!user) return Response.json({ error: "User not found" }, { status: 404 });

    const project = await prisma.project.findFirst({ where: { id: projectId, userId: user.id } });
    if (!project) return Response.json({ error: "Project not found" }, { status: 404 });

    const body = await request.json();
    const parsed = transcribeSchema.safeParse(body);
    if (!parsed.success) {
      return Response.json({ error: "Invalid request", details: parsed.error.flatten() }, { status: 400 });
    }

    const mediaFile = await prisma.mediaFile.findFirst({
      where: { id: parsed.data.mediaFileId, projectId },
    });
    if (!mediaFile) return Response.json({ error: "Media file not found" }, { status: 404 });
    if (!mediaFile.audioUrl && !mediaFile.storageUrl) {
      return Response.json({ error: "Media file has no audio URL" }, { status: 400 });
    }

    const job = await prisma.job.create({
      data: {
        projectId,
        type: "TRANSCRIPTION",
        status: "PENDING",
        progress: 0,
        metadata: {
          mediaFileId: mediaFile.id,
          provider: parsed.data.provider ?? "WHISPER",
          language: parsed.data.language,
        },
      },
    });

    await prisma.project.update({ where: { id: projectId }, data: { status: "PROCESSING" } });

    runTranscriptionInBackground(job.id, mediaFile, parsed.data, projectId).catch(console.error);

    return Response.json({ jobId: job.id, status: "PENDING" }, { status: 202 });
  } catch (error) {
    console.error("[POST /api/projects/[id]/transcribe]", error);
    return Response.json({ error: "Internal server error" }, { status: 500 });
  }
}

async function runTranscriptionInBackground(
  jobId: string,
  mediaFile: { id: string; audioUrl: string | null; storageUrl: string | null },
  options: z.infer<typeof transcribeSchema>,
  projectId: string
) {
  try {
    await prisma.job.update({
      where: { id: jobId },
      data: { status: "PROCESSING", startedAt: new Date(), progress: 10 },
    });

    const provider = options.provider
      ? getSTTProvider(options.provider)
      : getDefaultSTTProvider();

    const audioUrl = mediaFile.audioUrl ?? mediaFile.storageUrl!;

    const result = await provider.transcribe(audioUrl, {
      provider: options.provider ?? "WHISPER",
      language: options.language,
      diarization: options.diarization,
      punctuation: options.punctuation,
      wordTimestamps: options.wordTimestamps,
    });

    await prisma.job.update({ where: { id: jobId }, data: { progress: 70 } });

    const track = await prisma.subtitleTrack.create({
      data: {
        projectId,
        mediaFileId: mediaFile.id,
        language: result.language,
        provider: options.provider ?? "WHISPER",
        confidence: result.confidence,
        isDefault: true,
        isAutoGenerated: true,
        wordTimestamps: options.wordTimestamps,
      },
    });

    await prisma.subtitleSegment.createMany({
      data: result.segments.map((seg) => ({
        trackId: track.id,
        index: seg.index,
        startTime: seg.startTime,
        endTime: seg.endTime,
        text: seg.text,
        words: seg.words ? JSON.parse(JSON.stringify(seg.words)) : undefined,
        speaker: seg.speaker,
        confidence: seg.confidence,
      })),
    });

    await prisma.mediaFile.update({
      where: { id: mediaFile.id },
      data: { duration: result.duration },
    });

    await prisma.project.update({
      where: { id: projectId },
      data: { status: "READY", duration: result.duration },
    });

    await prisma.job.update({
      where: { id: jobId },
      data: {
        status: "COMPLETED",
        progress: 100,
        completedAt: new Date(),
        metadata: { trackId: track.id },
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    await prisma.job.update({
      where: { id: jobId },
      data: { status: "FAILED", error: message, completedAt: new Date() },
    });
    await prisma.project.update({ where: { id: projectId }, data: { status: "ERROR" } });
  }
}
