export type JobStatus = "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED" | "CANCELLED";
export type JobType = "TRANSCRIPTION" | "TRANSLATION" | "EXPORT" | "BURN" | "SUMMARY" | "CHAPTERS";
export type ExportFormat = "SRT" | "VTT" | "TXT" | "JSON" | "ASS";
export type TranscriptionProvider = "WHISPER" | "DEEPGRAM" | "ASSEMBLYAI";
export type ProjectStatus = "DRAFT" | "PROCESSING" | "READY" | "ERROR";

export interface WordTimestamp {
  word: string;
  start: number;
  end: number;
  confidence?: number;
}

export interface SubtitleStyle {
  bold?: boolean;
  italic?: boolean;
  underline?: boolean;
  color?: string;
  fontSize?: number;
  fontFamily?: string;
  align?: "left" | "center" | "right";
  position?: "top" | "bottom" | "custom";
  x?: number;
  y?: number;
}

export interface SubtitleSegment {
  id: string;
  trackId: string;
  index: number;
  startTime: number;
  endTime: number;
  text: string;
  words?: WordTimestamp[];
  speaker?: string | null;
  confidence?: number | null;
  style?: SubtitleStyle | null;
  createdAt: string;
  updatedAt: string;
}

export interface SubtitleTrack {
  id: string;
  projectId: string;
  mediaFileId: string;
  language: string;
  label?: string | null;
  provider?: TranscriptionProvider | null;
  confidence?: number | null;
  isDefault: boolean;
  isAutoGenerated: boolean;
  wordTimestamps: boolean;
  segments: SubtitleSegment[];
  createdAt: string;
  updatedAt: string;
}

export interface MediaFile {
  id: string;
  projectId: string;
  userId: string;
  originalName: string;
  mimeType: string;
  size: number;
  storageKey: string;
  storageUrl?: string | null;
  audioKey?: string | null;
  audioUrl?: string | null;
  waveformData?: number[] | null;
  thumbnailKey?: string | null;
  thumbnailUrl?: string | null;
  duration?: number | null;
  sampleRate?: number | null;
  channels?: number | null;
  bitrate?: number | null;
  width?: number | null;
  height?: number | null;
  fps?: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface User {
  id: string;
  clerkId: string;
  email: string;
  name?: string | null;
  avatarUrl?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Translation {
  id: string;
  projectId: string;
  trackId: string;
  sourceLanguage: string;
  targetLanguage: string;
  segments: { index: number; text: string }[];
  status: "PENDING" | "COMPLETED" | "FAILED";
  createdAt: string;
  updatedAt: string;
}

export interface Project {
  id: string;
  userId: string;
  title: string;
  description?: string | null;
  status: ProjectStatus;
  language: string;
  duration?: number | null;
  thumbnailUrl?: string | null;
  mediaFiles: MediaFile[];
  subtitleTracks: SubtitleTrack[];
  translations?: Translation[];
  jobs?: Job[];
  createdAt: string;
  updatedAt: string;
}

export interface Job {
  id: string;
  projectId: string;
  type: JobType;
  status: JobStatus;
  progress: number;
  metadata?: Record<string, unknown> | null;
  error?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface TranscriptionOptions {
  provider: TranscriptionProvider;
  language?: string;
  diarization?: boolean;
  punctuation?: boolean;
  wordTimestamps?: boolean;
}

export interface TranscriptionResult {
  segments: Omit<SubtitleSegment, "id" | "trackId" | "createdAt" | "updatedAt">[];
  language: string;
  confidence: number;
  duration: number;
}

export interface ExportOptions {
  format: ExportFormat;
  includeTimestamps?: boolean;
  includeStyles?: boolean;
  maxLineLength?: number;
  maxLinesPerSegment?: number;
}

export interface WaveformData {
  peaks: number[];
  duration: number;
  sampleRate: number;
}

export interface ChapterMarker {
  time: number;
  title: string;
  description?: string;
}

export interface AIToolResult {
  type: "summary" | "chapters" | "keywords" | "hashtags" | "description";
  content: string | ChapterMarker[];
}

export interface UploadProgress {
  loaded: number;
  total: number;
  percentage: number;
  speed?: number;
  eta?: number;
}

export interface SSEEvent {
  type: "progress" | "completed" | "error" | "status";
  jobId: string;
  data: Record<string, unknown>;
}
